export const USER_INITIAL_BOARD = 'USER_INITIAL_BOARD';
export const USER_HANDLE_CLICK = 'USER_HANDLE_CLICK';
export const USER_HANDLE_CHECK_WINNER_CHICKEN_DINNER = 'USER_HANDLE_CHECK_WINNER_CHICKEN_DINNER';
export const USER_HANDLE_PLAY_AGAINS = 'USER_HANDLE_PLAY_AGAINS';
export const USER_HANLDE_CHANGE_SETTING = 'USER_HANLDE_CHANGE_SETTING';
export const USER_HANLDE_TIME_OUT = 'USER_HANLDE_TIME_OUT';
export const USER_HANDLE_RESET_TIME = 'USER_HANDLE_RESET_TIME';

export const USER_HANDLE_CLOSE_MODAL = 'USER_HANDLE_CLOSE_MODAL';
export const USER_HANDLE_STEP_CLICK = 'USER_HANDLE_STEP_CLICK';
export const USER_HANLDE_CHANGLE_AFTER_PLAYER_CLICK = 'USER_HANLDE_CHANGLE_AFTER_PLAYER_CLICK';
export const USER_HANDLE_CHANGE_HISTORY_ORDER = 'USER_HANDLE_CHANGE_HISTORY_ORDER';
export const USER_HANDLE_MOUSE_OVER = 'USER_HANDLE_MOUSE_OVER';
export const USER_HANDLE_MOUSE_LEAVE = 'USER_HANDLE_MOUSE_LEAVE';
export const USER_HANDLE_SHOW_MODAL = 'USER_HANDLE_SHOW_MODAL';
export const USER_HANDLE_AFTER_RESTART_TIME = 'USER_HANDLE_AFTER_RESTART_TIME';

export const COUNT_DOWN = 'COUNT_DOWN';
export const USER_HANDLE_TAP_CHANGE = 'USER_HANDLE_TAP_CHANGE';
export const HANDLE_LOGIN = 'HANDLE_LOGIN';
export const HANDLE_CHANGE_INFO = 'HANDLE_CHANGE_INFO';
export const HANDLE_CHANGE_REGISTER_INFO = 'HANDLE_CHANGE_REGISTER_INFO';
export const HANDLE_REGISTER = 'HANDLE_REGISTER';
export const HANDLE_LOGOUT = 'HANDLE_LOGOUT';
export const HANDLE_CHECK_LOGIN = 'HANDLE_CHECK_LOGIN';
export const HANLDE_LOADING_LOGIN_ON = 'HANLDE_LOADING_LOGIN';
export const HANLDE_LOADING_LOGIN_OFF = 'HANLDE_LOADING_LOGIN';

export const HANDLE_CHANGE_SELECT = 'HANDLE_CHANGE_SELECT';
export const HANDLE_FINDING_MATCH = 'HANDLE_FINDING_MATCH';

export const HANDLE_DISABLE_AFTER_USER_CLICK = 'HANDLE_DISABLE_AFTER_USER_CLICK';
